DROP table if exists t_order;

create table t_order
(
    id    int generated by default as identity primary key,
    name  varchar(100)        not null,
    price decimal,
    time  timestamp with time zone not null default current_timestamp
)